from main import find_answer

test_set = 2
if test_set == 1:
    find_answer(['Si algo te importa un pimiento es que...','te toca las narices','es pan comido','no te importa nada'])
    find_answer(['¿Cuál de estas cantantes es conocida como “La Reina del Pop”?','madonna','amaia montero','edurne'])
    find_answer(['¿Cuál de estas obras NO pertenece al pintor Vincent Van Gogh?','la noche estrellada','los girasoles','la escuela de atenas'])
    find_answer(['¿De qué país africano es capital la ciudad de Adís Abeba?','etiopía','somalia','eritrea'])
    find_answer(['¿Qué estrella del sistema solar es la más cercana a la Tierra después del Sol?','alfa centauri','estrella de barnard','sirio'])
    find_answer(['¿En qué ámbito nos movemos si utilizamos el término “triforio”?','música','arquitectura','gramática'])
    find_answer(['¿Quién ocupa actualmente el cargo de Presidente del Consejo Europeo?','mario draghi','donald tusk','jean-claude juncker'])
    find_answer(['¿Cuál de estas unidades de almacenamiento es más grande?','petabyte','zettabyte','yottabyte'])
    find_answer(['¿A qué nos referimos cuando hablamos de las beguinas?','una comunidad laica de mujeres cristianas','una congregación de monjas de flandes','las novicias de las ursulinas'])
    find_answer(['¿Cuál de estos deportes se practica utilizando "piedras" y una "casa"?','jai alai','curling','lacrosse'])
    find_answer(['¿Cuál es el nombre original del monstruo de ficción conocido como Godzilla?','kiharo','gojira','kaihu'])
    find_answer(['¿Qué ministro de Hacienda llevó a cabo una desamortización en España en la segunda mitad del siglo XIX?','pascual madoz','juan álvarez mendizábal','manuel godoy'])
elif test_set == 2:
    find_answer(['¿Qué ingrediente NO utilizamos para elaborar la clásica tortilla española?','huevos','berenjena','patata'])
    find_answer(['¿Qué nombre recibe la cría de un conejo?','cervato','lechon','gazapo'])
    find_answer(['¿Cuál de estas novelas está protagonizada por el personaje de Lisbeth Salander?','los hombres que no amaban a las mujeres','la divina comedia','don juan tenorio'])
    find_answer(['¿Qué se propuso desarrollar el Proyecto Manhattan en 1941?','un avion supersonico','un cohete lunar','una bomba atomica'])
    find_answer(['¿Cómo se llama el sistema de medidas británico?','sistema metrico decimal','sistema duodecimal','sistema imperial'])
    find_answer(['¿A qué nos referimos cuando hacemos alusión a un “paletoque”?','un instrumento de escultor','una prenda de vestir','una herramienta de albañil'])
    find_answer(['¿Con cuántos países comparte frontera terrestre España?','3','4','5'])
    find_answer(['¿Cuál de estos pintores franceses es el autor de la obra “Juramento del juego de la pelota”?','Eugène delacroix','jacques-louis david','théodore géricault'])
    find_answer(['¿Cuál de estas opciones NO es una modalidad deportiva de invierno?','telemark','mushing','jailstyle'])
    find_answer(['¿Qué quiere decir el nombre del sistema de navegación por satélite desarrollado por China?','osa mayor','brújula','galaxia'])
    find_answer(['¿Cuál fue la primera película estadounidense en mostrar un inodoro con agua circulando?','leaving las vegas','psicosis','la semilla del diablo'])
    find_answer(['¿Qué banda de rock ha llevado a cabo la gira con mayor recaudación de la historia?','the rolling stones','u2','coldplay'])
elif test_set == 3:
    find_answer(['¿queé campesina llevó al ejército francés a conseguir varias victorias en el campo de batalla?','coco chanel','penélope glamour','juana de arco'])
    find_answer(['¿en qué ciudad nació el pintor pablo picasso?','málaga','sevilla','barcelona'])
    find_answer(['mide la cantidad de lluvia que cae en un lugar y en un espacio de tiempo determinados?','hidrógrafo','pluviómetro','termómetro'])
    find_answer(['¿cuál es el nombre actual del país que en su día se llamó persia?','irak','irán','afganistán'])
    find_answer(['¿cuál es el significado en español del acrónimo var?','árbitro asistente de vídeo','vídeo arbitraje por repetición','rectificación de arbitraje por vídeo'])
    find_answer(['¿a qué nos estamos refiriendo al utilizar el término "hayuco"?','un pequeño barco','un fruto','un tambor de madera de haya'])
    find_answer(['¿a qué grupo de la tabla periódica pertenece el francio?','alcalinos','alcalinotérreos','halógenos'])
    find_answer(['¿quién interpretó el personaje de george costanza en la serie de televisión seinfeld?','jason alexander','john malkovich','stuart templeton'])
    find_answer(['de los tres siguientes, uno no es un mago azul en la saga del señor de los anillos:','alatar','pallando','radagast'])
    find_answer(['¿a cuál de estas novelas pertenece el personaje de la maga?','luces de bohemia','alicia en el país de las maravillas','rayuela'])
    find_answer(['¿cual de estos tenistas consiguió ganar los cuatro torneos de grand slam en un mismo año?','bjorn borg','roger federer','rod laver'])
elif test_set == 4:
    find_answer(['¿Cuál de estos personajes NO fue un emperador del Imperio Romano?','Nerón','Alfonso XIII','Calígula'])
    find_answer(['¿En qué convertía el Rey Midas todo lo que tocaba según el cuento?','Plata','Polvo','Oro'])
    find_answer(['¿En cuál de estas series de televisión interpretó un papel protagonista Antonio Resines?','Los Soprano','Los Serrano','Médico de Familia'])
    find_answer(['¿Cuál es la moneda de curso legal que se utiliza en Turquía?','Kuna','Lira','Euro'])
    find_answer(['¿Para qué se utiliza el glicol de etileno en los automóviles?','Anticongelante','Sistema de frenos','Dirección hidráulica'])
    find_answer(['¿A qué nos referimos cuando hacemos alusión a una “hubara”?','Una avutarda','Un instrumento de cuerda','Una camisola medieval'])
    find_answer(['¿En cuál de los siguientes países se conduce por la izquierda?','Malawi','Madagascar','Yemen'])
    find_answer(['¿Cómo se conoce al punto del océano más alejado de tierra firme?','Punto Barrow','Punto Nui','Punto Nemo'])
    find_answer(['¿Cómo se llama la finca que posee Charles Foster Kane en la película “Ciudadano Kane”?','Neverland','Xanadú','Bramasole'])
    find_answer(['¿Cuál de estos atletas consiguió ganar un maratón olímpico corriendo descalzo?','Haile Gebrselassie','Abebe Bikila','Kenenisa Bekele'])
    find_answer(['¿A qué músico pertenece el álbum "The Cry of Love" de 1970?','Jimi Hendrix','Janis Joplin','James Morrison'])
    find_answer(['¿Gracias a qué hizo fortuna el pintor Claude Monet?','Nunca hizo fortuna','Auge de la industria minera','Un premio de lotería'])
elif test_set == 5:
    #2018-12-06
    find_answer(['¿Cuál de estas cantantes ha representado alguna vez a España en el Festival de Eurovisión?','Ana Guerra','Edurne','Merche'])
    find_answer(['¿Cuál de estos monarcas NO ha sido Jefe de Estado en España?','Juan Carlos I','Enrique VIII','Felipe II'])
    find_answer(['Al ángulo cuya amplitud es superior a 0º e inferior a 90º se le conoce como ángulo:','Agudo','Llano','Recto'])
    find_answer(['¿En qué videojuego se usó por primera vez el término "1-up" para designar una vida extra?','Pacman','Super Mario Bros.','Zelda'])
    find_answer(['¿Qué aparece en el anverso de los billetes de Euro?','Rostros ilustres','Puertas y ventanas','Montañas y ríos'])
    find_answer(['¿A qué nos estamos refiriendo al utilizar el término “aljófar”?','Un tipo de cofre','Un dulce árabe','Una perla pequeña'])
    find_answer(['¿Qué otro nombre recibe la fruta conocida como pitahaya?','Fruta de dragón','Fruta de la pasión','Tamarindo'])
    find_answer(['¿Cuál de estos países NO limita con Argelia?','Malí','Níger','Chad'])
    find_answer(['¿Cuál de estos actores de cine NO ha ganado nunca un premio Oscar?','Liam Neeson','Frank Sinatra','Nicolas Cage'])
    find_answer(['¿Cuál de estas novelas fue la primera escrita por H.G. Wells?','La máquina del tiempo','La guerra de los mundos','La isla del Doctor Moreau'])
    find_answer(['¿Cuál de estos jugadores de la selección española ha marcado más goles en partidos de la Copa del Mundo?','Fernando Torres','Fernando Morientes','Telmo Zarra'])
    find_answer(['¿Cuál de estas mujeres fue la primera en dar un paseo por el espacio?','Valentina Tereshkova','Svetlana Savistkaya','Kathryn D. Sullivan'])
elif test_set == 6:
    # find_answer(['¿Cuál de estos actores de cine NO ha ganado nunca un premio Oscar?','Liam Neeson','Frank Sinatra','Nicolas Cage'])
    # find_answer(['¿Cuál de estos jugadores de la selección española ha marcado más goles en partidos de la Copa del Mundo?','Fernando Torres','Fernando Morientes','Telmo Zarra'])
    # find_answer(['¿Con cuántos países comparte frontera terrestre España?','3','4','5'])
    find_answer(['¿Quién dirigió la película de animación “Pesadilla antes de Navidad”?','Wes Anderson','Henry Selick','Tim Burton'])
    find_answer(['¿Qué banda de rock ha llevado a cabo la gira con mayor recaudación de la historia?','the rolling stones','u2','coldplay'])
elif test_set == 7:
    find_answer(['Continúa el siguiente refrán “Es mejor lo malo conocido…”:','Que dos carretas','Que lo bueno por conocer','Que por diablo'])
    find_answer(['¿Cuál de estos NO es un tema del cantante David Bisbal?','Ave María','Alegría','Bulería'])
    find_answer(['¿En qué posición se encuentra la luz roja de un semáforo?','Arriba','Centro','Abajo'])
    find_answer(['¿Qué equipo de fútbol de la Primera División juega sus partidos como local en el Estadio de Montilivi?','RCD Espanyol','Girona FC','SD Huesca'])
    find_answer(['¿Qué actor interpreta el personaje de Elliot Alderson en la serie Mr Robot?','Sami Malek','Christian Slater','Rami Malek'])
    find_answer(['La distancia entre el Polo Norte magnético y el geográfico es:','Fija','Variable','No hay distancia'])
    find_answer(['¿A qué nos referimos cuando hablamos de un hachón?','Una guadaña de siega','Un cirio grande','Un tipo de garza'])
    find_answer(['¿Cuál de los siguientes filósofos NO fue representante de alguna corriente de la Escuela Hedonista?','Aristipo de Cirene','Tales de Mileto','Epicuro de Samos'])
    find_answer(['¿En cuál de estas películas se rechazó la participación como director de Steven Spielberg?','Poltergeist','La espía que me amó','Los Goonies'])
    find_answer(['¿De dónde procede el término "prensa amarilla o amarillista"?','De su origen en Hong Kong','Del personaje The Yellow Kid','Ninguna de las anteriores'])
    find_answer(['¿Por qué motivo es conocido el volcán indonesio de Kawah Ijen?','Por el color de su lava','Por la forma de su cráter','Por ser submarino'])
    find_answer(['¿En qué se basó el autor de El mago de Oz para nombrar a este país ficticio?','En el apodo de un familiar','En un archivador','En una tienda de artículos de magia'])
